export interface ProficiencyData {
  armor: string[];
  weapons: string[];
  tools: string[];
  languages: string[];
}

export interface ProficiencyFile {
  path: string;
  content: string;
}

export function renderProficiencyFile(charName: string, profs: ProficiencyData, basePath: string): ProficiencyFile {
  const toRow = (items: string[], category: string) =>
    `| **${category}** | ${items.length > 0 ? items.join(", ") : "—"} |`;

  const content = `---
character: "${charName}"
tags:
  - dnd/proficiencies
  - dnd/${charName.toLowerCase().replace(/\s+/g, "-")}
---

# ${charName} — Proficiencies & Training

| Category | Proficiencies |
|----------|--------------|
${toRow(profs.armor, "Armor")}
${toRow(profs.weapons, "Weapons")}
${toRow(profs.tools, "Tools")}
${toRow(profs.languages, "Languages")}

> Auto-generated by DnD Beyond Sync · ${new Date().toLocaleString()}
`;

  return {
    path: `${basePath}/Proficiencies.md`,
    content,
  };
}
